In [13]:
import os
from PIL import Image
path = 'C:\\Users\\Rishika\\Downloads\\challenge\\challenge'
# Store the image file names in a list as long as they are jpgs
images = []
for f in os.listdir(path):
    if os.path.splitext(f)[-1] == '.jpg':
        images.append(os.path.join(path, f))    
images
names = [name for name in os.listdir(path) if (name.endswith(".jpg") or name.endswith(".JPG")) ]
wt = []
ht = []
avg_bright = []
for i in range(len(images)):
    image = Image.open(images[i])
               
    # Calculating height and width
    height, width = image.size
    ht.append(height)
    wt.append(width)  
    # Calculating average brightness
    greyscale_image = image.convert('L')
    histogram = greyscale_image.histogram()
    pixels = sum(histogram)
    brightness = scale = len(histogram)

    for index in range(0, scale):
        ratio = histogram[index] / pixels
        brightness += ratio * (-scale + index)\

    avg_brightness = brightness/scale
    avg_bright.append(avg_brightness)
  
import pandas as pd
column_names = ["Name","Height","Width","Avg Brightness"]
data = pd.DataFrame(index=range(len(images)), columns=col_names)
for i in range(len(images)):
    data.iloc[i,0] = names[i]
    data.iloc[i,1] = ht[i]
    data.iloc[i,2] = wt[i]
    data.iloc[i,3] = avg_bright[i]

In [14]:
data

,Name,Height,Width,Avg Brightness
0,0ceeee70574721.5ba880832b068.jpg,1200,1634,0.419809
1,1.jpg,320,400,0.450632
2,2009_IT_1549000833211.JPG,594,746,0.360735
3,5658a73abbf4d.image.jpg,433,650,0.198731
4,akhilesh-yadav-on-the-cover-of-india-today-mag...,843,1144,0.442725
5,c2efbe9cf1b7457f2b24003c04e6e590.jpg,389,543,0.446189
6,"india-today-december-26,-2011---anniversary-is...",760,1054,0.479965
7,IN_INDIATO2014MTH05DT2601_B.jpg,390,543,0.52034
8,modi13_650_122112035215.jpg,391,543,0.602086
9,modi1_650_122112042518.jpg,389,543,0.529491
10,modi2_650_122112035215.jpg,390,543,0.382371
11,modi3_650_122112035215.jpg,391,543,0.471341
12,modi4_650_122112035215.jpg,1079,1494,0.409231
13,page_1.jpg,385,543,0.576575
14,rahul1-1_012513112423.jpg,384,543,0.534153
15,rahul4-1_012513112423.jpg,391,543,0.505511
16,rahul5-1_012513112423.jpg,377,543,0.569797